Update to include  V70 support
Xilinx/Alveo-Cards pull request #4
Opened 2023-06-14 15:13 UTC by sgbhargava

2023-06-14 15:14 UTC, sgbhargava commented
@ryanvergel Please let me know if there has been any updates to the themes or templates

2023-06-14 19:05 UTC, sgbhargava commented
Thanks @ryanvergel I have updated the theme

2023-06-15 21:19 UTC, krishna-xilinx commented on master/management-specification/doc/appendix_a.rst
> ++-------------------------+----------------------------------------------+
Edit line 65 as V70PQ2 QDMA
Add another line/row before V70PQ2. 
```
+-------------------------+----------------------------------------------+
V70 QDMA                | PF0=0x5094 PF1=0x5095 PF2=0x5096 PF3=0x5097
+-------------------------+----------------------------------------------+
```

2023-06-15 21:20 UTC, krishna-xilinx requested changes
pls add V70PQ2 PCIe info as mentioned

2023-06-16 16:57 UTC, krishna-xilinx approved these changes

2023-06-16 17:17 UTC, krishna-xilinx approved these changes

2023-06-16 17:18 UTC, merged